# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('aid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('atitle', models.CharField(max_length=30)),
                ('apid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Areas')),
            ],
            options={
                'db_table': 'areas',
            },
        ),
    ]
