# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='user/')),
            ],
            options={
                'db_table': 'picture',
            },
        ),
    ]
